version: "3.2"

services:
  nginx:
    container_name: site
    image: bitnami/nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./docker/nginx/site.conf:/opt/bitnami/nginx/conf/server_blocks/site.conf:ro
      - ./app:/app